export const ADD_TODO = "ADD_TODO";
export const ADD_RANDOM_EMAIL = "ADD_RANDOM_EMAIL";
export const TEXT_FETCH_SUCCEEDED = "TEXT_FETCH_SUCCEEDED";
export const USER_FETCH_FAILED = "USER_FETCH_FAILED";
